controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

# RECOMMENDED METHOD TO APPLY ROUTES IS THROUGH PHP ATTRIBUTES
# KEEP THIS FILE CLEAR